apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: msa-gateway
spec:
  selector:
    istio: ingressgateway # Istio 기본 인그레스 게이트웨이 사용
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: msa-vs
spec:
  hosts:
  - "*"
  gateways:
  - msa-gateway
  http:
  # 1. /user 로 시작하는 요청은 User Pod로
  - match:
    - uri:
        prefix: /user
    route:
    - destination:
        host: svc-fastapi-user
        port:
          number: 8000
          
  # 2. /market 로 시작하는 요청은 Market Pod로
  - match:
    - uri:
        prefix: /market
    route:
    - destination:
        host: svc-fastapi-market
        port:
          number: 8000
          
  # 3. /posts 로 시작하는 요청은 Posts Pod로
  - match:
    - uri:
        prefix: /posts
    route:
    - destination:
        host: svc-fastapi-posts
        port:
          number: 8000
          
  # 4. 그 외 모든 요청(/)은 Index Pod로
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: svc-fastapi-index
        port:
          number: 8000