# step10_ansible/inventory.ini 파일

[workers]
172.16.8.11
172.16.8.12

[workers:vars]
ansible_user=root
# 실제 root 비밀번호.
ansible_password=test123
# SSH 최초 접속 시 known_hosts 확인(yes/no) 프롬프트 무시
ansible_ssh_common_args='-o StrictHostKeyChecking=no'