---
# Source: syntax-study/templates/deploy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  # 문자열이 들어 있는 배열을 순회하면서 원하는 내용 출력하기 
  # . 형식으로 현재 item 을 참조 할수 있다
  domain-www: "www.cloud-learning.site"
  domain-mail: "mail.cloud-learning.site"
  domain-argocd: "argocd.cloud-learning.site"
