---
- name: 모든 노드에 NFS 클라이언트 패키지(nfs-common) 설치
  hosts: all
  become: true  # sudo 권한으로 실행 (sudo apt-get ...)
  tasks:
    - name: apt 패키지 캐시 업데이트 및 nfs-common 설치
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: true  # apt-get update 효과