# values.yaml 

ingress:
  enabled: true
  className: "nginx"
  host: "cloud-learning.site" #  도메인을 동적 주입
 
  # 마이크로서비스 경로 구조를 배열 형태로 깔끔하게 관리!
  paths:
    - path: /market
      pathType: Prefix
      serviceName: svc-market-app
      port: 8000
    - path: /posts
      pathType: Prefix
      serviceName: svc-post-app
      port: 8000
    - path: /
      pathType: Prefix
      serviceName: svc-index-app
      port: 80