# my-values.yaml

# ArgoCD 웹서버(ui) 의 네트워크 설정 전달하기
server:
  service:
    # ingress 를 통해서 접속할 예정이기 때문에 type 을 ClusterIP 로 설정한다
    type: ClusterIP
  # cloudflared 또는 route53 을 거쳐서 https 처리는 다되어서 들어오기 때문에 --insecure 로 설정한다 
  extraArgs:
    - --insecure