# deploy-cloudflared.yaml 파일
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: default # 파드가 배포될 네임 스페이스 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        # cloudflared 에서 제공해주는 이미지를 사용한다 
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate # 컨테이너 자체의 자동 업데이트 차단 
        - run
        env:
        # TUNNEL_TOKEN 이라는 이름의 환경변수로 터널 토큰을 secret 로 부터 주입받기 
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: tunnel-credentials
              key: token